# Generated by Django 4.2 on 2023-04-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level1', to='menu.menu0')),
            ],
        ),
        migrations.CreateModel(
            name='Menu2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level2', to='menu.menu1')),
            ],
        ),
        migrations.CreateModel(
            name='Menu3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3', to='menu.menu2')),
            ],
        ),
        migrations.CreateModel(
            name='Menu4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level3', to='menu.menu3')),
            ],
        ),
    ]
