# Generated by Django 4.2 on 2023-04-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu1_code_menu2_code_menu3_code_menu4_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu0',
            name='code',
            field=models.CharField(default='1', max_length=64),
        ),
    ]
